wandb:
  wandb_log: True
  name: 'OOD Donor: '
  project: 'SCDISENTANGLE REPRODUCE'
  group: 'Myocarditis ORG split_key pre_steroid'

UI:
  launch: False
  ide: True

hardware:
  device: 0

other:
  experiment_name: True
  verbose: True

data: 
  file_path: '/data/Experiments/Benchmark/SCDISENTANGLE_REPRODUCE/Datasets/preprocessed_datasets/myocarditis_org_pre_steroid.h5ad'
  default_normalization: False
  use_counts: True
  label_keys: ['donor', 'tissue', 'on_steroids', 'sc_cell_ids', 'cell_type']

  highly_variable: False
  min_gene_counts: False
  min_cell_counts: False
  train_size: 1
  val_size: 0
  test_size: 0
  batch_size: 128
  crispr_data: False
  SUBSET: False

OOD: 
  apply: True
  filter_dict:
    tissue: 'Heart'
    donor: 'Insert'

growing_neurons:
  total_neurons: 16
  lr: 0.001
  decoder_name: 'decoder_post_train'

  prior_mappers:
    mappers:
      tissue_mapper:
        name: 'tissue'
        embedder_name: 'tissue_embedder'

        collapse_name: 'Heart'
        collapse_target: True

      donor_mapper:
        name: 'donor'
        embedder_name: 'donor_embedder'

        collapse_name: 'Insert_OOD'
        collapse_target: False

models:
  encoder_pretrain: 
    layers: [5000, 256, 16]
    hidden_activation: 'Sine'
    last_activation: 'Sine'
    xavier_init: True
    batch_norm: False

  decoder:
    layers: [16, 1024, 1024, 1024, 5000]
    hidden_activation: 'Sine'
    last_activation: False
    xavier_init: True
    batch_norm: False 

  encoder:
    layers: [16, 256, 1]
    hidden_activation: 'Sine'
    last_activation: 'Sine'
    xavier_init: True
    batch_norm: False
 
  mapper: 
    layers: [1, 256, 16]
    hidden_activation: 'Sine'
    last_activation: 'Sine'
    xavier_init: True
    batch_norm: False
  
decoder_parameters:
  use_scvi_decoder:
    apply: True
    n_layers: 3
    n_hidden: 1024
    
    #pxr_lr: 0.0001 #0.001

embedders:
  tissue_embedder:
    n_classes: 2
    n_dim: 2

  donor_embedder:
    n_classes: 12
    n_dim: 4

optimizers: 
  condition_optimizers:
    models: ['tissue_embedder', 'donor_embedder']
    lr: [0.001, 0.001]

  decoder_optimizer:
    models: ['encoder_pretrain', 'decoder']
    lr: [0.0001, 0.0001, 0.0001] #IThird for PXR !

losses:

  rec_from_latent_pretrain:
    fnc_name: 'nb_loss'
    apply: True
    pred_key: 'px_l'
    gt_key: 'x_inp'
    activate_at: 0
    stop_at: +.inf
    weight:  0.00001
    gradient_flow: 'all'

  recover_latent:
    fnc_name: 'recover_latent'
    apply: True
    latent_key: 'pre_latent'
    post_latent_key: 'map_latent_summed'
    activate_at: 0
    stop_at: +.inf
    weight: 0.002
    gradient_flow: 'all'

 
train:
  set_seed: 1
  
  main_train:
    epochs: 521

  evaluate: True

  criterions:

    r2_mean_criterion/10_all:
      criterion: 'max'

evaluations:
  context_transfer_criterion:
    interval: 40
    start_eval: 0
    stop_eval: +.inf
    dataloaders: ['all']
    kwargs:
      rec_key: 'reconstructed_collapse'
      gt_key: 'x_inp' #
      adata_degs_key: 'rank_genes_groups_tissue' #
      variables_of_interest: ['tissue', 'donor']
      stim_name: 'Heart'
      eval_by: 'donor'
      subset_covars: False #["SIC_258","SIC_199","SIC_264","SIC_48","SIC_197","SIC_164","SIC_217","SIC_153","SIC_171"]
      ood_covariate: 'Insert_OOD' # Should be dynamic
      normalize_log: True
      n_degs_list: [10, 20, 50, 100]

      metrics: ['r2_mean', 'r2_delta', 'wasserstein', 'r2_var']
      wasserstein_degs_list: [10]
      
      subsample:
        gt:
          tissue: 'Heart'

        pred:
          tissue: 'Blood'

        ctrl:
          tissue: 'Blood'

        collapse:
          tissue_mapper:
            apply: False
            collapse_name: null
          donor_mapper:
            apply: False
            collapse_name: null

  evaluate_reconstruction:
    interval: 40
    start_eval: 0
    stop_eval: +.inf
    dataloaders: ['train']
    kwargs:
      rec_key: 'reconstructed'
      gt_key: 'x_inp'

  get_mig:
    interval: 40
    start_eval: 0
    stop_eval: +.inf
    dataloaders: ['train']
    kwargs:
      latent_key: 'dis_latent_stack'
      label_keys: ['tissue']

save_experiment:
  apply: True
  experiment_path: 'weights/' #'experiments/oods1_2048bs_meanfix'
  save_weights:
    apply: True
    interval: 200
    
  save_best_weights:
    apply: True

save_gradients: 
  apply: True
  interval: 100
