wandb:
  wandb_log: True
  name: ''
  project: 'SCDISENTANGLE REPRODUCE'
  group: 'SC: Liver HPI'

UI:
  launch: False
  ide: True

hardware:
  device: 0

other:
  experiment_name: True
  verbose: True

data: 
  file_path: '/data/Experiments/Benchmark/SCDISENTANGLE_REPRODUCE/Datasets/preprocessed_datasets/liver.h5ad'
  default_normalization: False
  use_counts: True
  label_keys: ['status_control', 'zone', 'infected', 'time', 'coarse_time']

  highly_variable: False
  min_gene_counts: False
  min_cell_counts: False
  train_size: 1
  val_size: 0
  test_size: 0
  batch_size: 128
  crispr_data: False
  SUBSET: False

OOD: 
  apply: False #True
  filter_dict:
    status_control: 'Infected'
    zone: 'Insert'

growing_neurons:
  total_neurons: 16 #8
  lr: 0.001
  decoder_name: 'decoder_post_train'

  prior_mappers:
    mappers:
      status_control_mapper:
        name: 'status_control'
        embedder_name: 'status_control_embedder'

        collapse_name: 'Infected'
        collapse_target: True

      coarse_time_mapper:
        name: 'coarse_time'
        embedder_name: 'coarse_time_embedder'

        collapse_name: '36 hpi'
        collapse_target: True

      zone_mapper:
        name: 'zone'
        embedder_name: 'zone_embedder'

        collapse_name: 'Insert_OOD'
        collapse_target: False

models:
  encoder_pretrain: 
    layers: [8203, 256, 16]
    hidden_activation: 'Sine'
    last_activation: 'Sine'
    xavier_init: True
    batch_norm: False

  decoder:
    layers: [16, 1024, 1024, 1024, 8203]
    hidden_activation: 'Sine'
    last_activation: False
    xavier_init: True
    batch_norm: False 

  encoder:
    layers: [16, 256, 1]
    hidden_activation: 'Sine'
    last_activation: 'Sine'
    xavier_init: True
    batch_norm: False
 
  mapper: 
    layers: [1, 256, 16]
    hidden_activation: 'Sine'
    last_activation: 'Sine'
    xavier_init: True
    batch_norm: False
  
decoder_parameters:
  use_scvi_decoder:
    apply: True
    n_layers: 3
    n_hidden: 1024

embedders:
  status_control_embedder:
    n_classes: 3
    n_dim: 2

  zone_embedder:
    n_classes: 2
    n_dim: 2

  coarse_time_embedder:
    n_classes: 6 
    n_dim: 2

optimizers: 
  condition_optimizers:
    models: ['status_control_embedder', 'zone_embedder', 'coarse_time_embedder']
    lr: [0.001, 0.001, 0.001]

  decoder_optimizer:
    models: ['encoder_pretrain', 'decoder']
    lr: [0.0001, 0.0001, 0.0001]

losses:

  rec_from_latent_pretrain:
    fnc_name: 'nb_loss'
    apply: True
    pred_key: 'px_l'
    gt_key: 'x_inp'
    activate_at: 0
    stop_at: +.inf
    weight:  0.00001
    gradient_flow: 'all'

  recover_latent:
    fnc_name: 'recover_latent'
    apply: True
    latent_key: 'pre_latent'
    post_latent_key: 'map_latent_summed'
    activate_at: 0
    stop_at: +.inf
    weight: 0.002
    gradient_flow: 'all'

 
train:
  set_seed: 1
  
  main_train:
    epochs: 521 #1001

  evaluate: True

  criterions:

    r2_mean_criterion/10_all:
      criterion: 'max'

evaluations:
  context_transfer_criterion:
    interval: 40
    start_eval: 0
    stop_eval: +.inf
    dataloaders: ['all']
    kwargs:
      rec_key: 'reconstructed_collapse'
      gt_key: 'x_inp' #
      adata_degs_key: 'rank_genes_groups_hpi'
      variables_of_interest: ['status_control', 'zone', 'coarse_time']
      stim_name: '36 hpi'
      eval_by: 'zone'
      subset_covars: False
      ood_covariate: 'Insert_OOD' # Should be dynamic
      normalize_log: True
      n_degs_list: [10, 20, 50, 100]

      metrics: ['r2_mean', 'r2_delta', 'wasserstein', 'r2_var', 'pear_var']
      wasserstein_degs_list: [10, 100]
      
      subsample:
        gt:
          status_control: 'Infected'
          coarse_time: '36 hpi'

        pred:
          status_control: 'Control'

        ctrl:
          status_control: 'Control'

        collapse:
          status_control_mapper:
            apply: False
            collapse_name: null
          zone_mapper:
            apply: False
            collapse_name: null

  evaluate_reconstruction:
    interval: 40
    start_eval: 0
    stop_eval: +.inf
    dataloaders: ['train']
    kwargs:
      rec_key: 'reconstructed'
      gt_key: 'x_inp'

  get_mig:
    interval: 40
    start_eval: 0
    stop_eval: +.inf
    dataloaders: ['train']
    kwargs:
      latent_key: 'dis_latent_stack'
      label_keys: ['status_control']

save_experiment:
  apply: True
  experiment_path: 'weights/'
  save_weights:
    apply: True
    interval: 200
    
  save_best_weights:
    apply: True

save_gradients: 
  apply: True
  interval: 100